[versions]

axion-release-plugin = "1.21.0"
kotlin-jvm = "2.2.21"

ksp = "2.3.2"

mockk = "1.14.6"
jacoco = "0.8.14"
testkit-jacoco-plugin = "1.0.4"

[libraries]

ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }

[plugins]

axion-release-plugin = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release-plugin" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

testkit-jacoco-plugin = { id = "io.github.gmazzo.gradle.testkit.jacoco", version.ref = "testkit-jacoco-plugin" }
